### ISSUE TITLE
Enforce paths on git.

### ISSUE THREAD

**Issue by hibooboo2** [shaftoe/godevsum#1]
https://github.com/shaftoe/godevsum/blob/master/repo.go#L41

Why are u enforcing a git path on the user. Just take any path and see if it is git. Shouldn't require then to install git where you want it.

**Comment by shaftoe** [comment]
@hibooboo2 this was to support [OpenWhisk dockerized actions](https://www.ibm.com/blogs/bluemix/2017/01/docker-bluemix-openwhisk/), which does not have any Git available, so [here](https://github.com/shaftoe/lastversion) I had to ship a statically linked git binary togther with the Go app using this lib, but yes, I like your suggestion of getting from PATH instead and falling back to "/action/git" if not found, or fail

**Comment by shaftoe** [comment]
@hibooboo2 I still want the user to be able to set the alternative git path, but should be a bit cleaner now: https://github.com/shaftoe/godevsum/pull/2

**Comment by shaftoe** [comment]
PR merged
